### ISSUE TITLE
cannot load such file -- bundler/setup (LoadError)

### ISSUE THREAD

**Issue by krisfish1** [matheussilvasantos/dynamocli#6]
I'm running AmazonLinux 2

(venv) -bash-4.2# dynamocli import csv-convert.py 
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/dynamocli-0.1.6/bin/dynamocli:3:in `<top (required)>'
        from /usr/local/bin/dynamocli:23:in `load'
        from /usr/local/bin/dynamocli:23:in `<main>'

**Comment by matheussilvasantos** [comment]
Hello, sorry for the long, long time delay.

How have you installed Ruby? Also, I realised that `dynamocli` needs Ruby greater or equals to 2.3. I'll update that in RubyGems.

**Comment by stanglt** [comment]
Hey,

had the same error. Installing bundler solved the issue.

`gem install bundler`
